// <auto-generated />
using System;
using LogicaAccesoDatos.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LogicaAccesoDatos.Migrations
{
    [DbContext(typeof(ProyectoContext))]
    partial class ProyectoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LogicaNegocio.Entidades.Dia", b =>
                {
                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("Horas")
                        .HasColumnType("int");

                    b.Property<int?>("ObraEmpleadoIdEmpleado")
                        .HasColumnType("int");

                    b.Property<int?>("ObraEmpleadoIdObra")
                        .HasColumnType("int");

                    b.HasKey("Fecha");

                    b.HasIndex("ObraEmpleadoIdObra", "ObraEmpleadoIdEmpleado");

                    b.ToTable("Dias");
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Banco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CuentaBanco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdEmpleado");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ObraIdObra")
                        .HasColumnType("int");

                    b.Property<int?>("ObraIdObra1")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("UnidadDeMedida")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ObraIdObra");

                    b.HasIndex("ObraIdObra1");

                    b.ToTable("Materiales");
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.Obra", b =>
                {
                    b.Property<int>("IdObra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdObra"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaFinalizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Finalizada")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdObra");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("Obras");
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.ObraEmpleado", b =>
                {
                    b.Property<int>("IdObra")
                        .HasColumnType("int");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaEgreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.HasKey("IdObra", "IdEmpleado");

                    b.ToTable("ObrasEmpleados");
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.Plano", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaPublicado")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdPlano")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ObraIdObra")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdPlano");

                    b.HasIndex("ObraIdObra");

                    b.ToTable("Planos");
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.Solicitud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AprovadorId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdObra")
                        .HasColumnType("int");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("int");

                    b.Property<int>("IdUDeOficina")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("SolicitanteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AprovadorId");

                    b.HasIndex("IdObra");

                    b.HasIndex("IdProveedor");

                    b.HasIndex("SolicitanteId");

                    b.ToTable("Solicitudes");
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.TipoEmpleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoría")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Compensacion")
                        .HasColumnType("float");

                    b.Property<double>("Presentismo")
                        .HasColumnType("float");

                    b.Property<double>("ValorHora")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("TiposEmpleados");
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.TipoPlano", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TiposPlanos");
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contrasenia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Usuario");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.UDeOficina", b =>
                {
                    b.HasBaseType("LogicaNegocio.Entidades.Usuario");

                    b.HasDiscriminator().HasValue("UDeOficina");
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.Dia", b =>
                {
                    b.HasOne("LogicaNegocio.Entidades.ObraEmpleado", null)
                        .WithMany("Dias")
                        .HasForeignKey("ObraEmpleadoIdObra", "ObraEmpleadoIdEmpleado");
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.Empleado", b =>
                {
                    b.HasOne("LogicaNegocio.Entidades.TipoEmpleado", "TipoEmpleado")
                        .WithMany()
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoEmpleado");
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.Material", b =>
                {
                    b.HasOne("LogicaNegocio.Entidades.Obra", null)
                        .WithMany("MaterialesObra")
                        .HasForeignKey("ObraIdObra");

                    b.HasOne("LogicaNegocio.Entidades.Obra", null)
                        .WithMany("MaterialesSolicitados")
                        .HasForeignKey("ObraIdObra1");
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.Obra", b =>
                {
                    b.HasOne("LogicaNegocio.Entidades.Empleado", null)
                        .WithMany("Obras")
                        .HasForeignKey("EmpleadoId");
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.Plano", b =>
                {
                    b.HasOne("LogicaNegocio.Entidades.TipoPlano", "TipoPlano")
                        .WithMany()
                        .HasForeignKey("IdPlano")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogicaNegocio.Entidades.Obra", null)
                        .WithMany("Planos")
                        .HasForeignKey("ObraIdObra");

                    b.Navigation("TipoPlano");
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.Solicitud", b =>
                {
                    b.HasOne("LogicaNegocio.Entidades.UDeOficina", "Aprovador")
                        .WithMany()
                        .HasForeignKey("AprovadorId");

                    b.HasOne("LogicaNegocio.Entidades.Obra", "Obra")
                        .WithMany("Solicitudes")
                        .HasForeignKey("IdObra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogicaNegocio.Entidades.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogicaNegocio.Entidades.Usuario", "Solicitante")
                        .WithMany()
                        .HasForeignKey("SolicitanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aprovador");

                    b.Navigation("Obra");

                    b.Navigation("Proveedor");

                    b.Navigation("Solicitante");
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.Empleado", b =>
                {
                    b.Navigation("Obras");
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.Obra", b =>
                {
                    b.Navigation("MaterialesObra");

                    b.Navigation("MaterialesSolicitados");

                    b.Navigation("Planos");

                    b.Navigation("Solicitudes");
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.ObraEmpleado", b =>
                {
                    b.Navigation("Dias");
                });
#pragma warning restore 612, 618
        }
    }
}
